### ISSUE TITLE
Cannot ind module 'yargs'

### ISSUE THREAD

**Issue by G0053-Ma5t3r** [clovisjohn/opensea-sniper-bot#2]
Hi I am getting this error.
Any idea what the issue could be?

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'yargs'
Require stack:
- /home/anon/opensea-sniper-bot/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/anon/opensea-sniper-bot/main.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/anon/opensea-sniper-bot/main.js' ]
}

**Comment by clovisjohn** [comment]
Do you have the yargs package installed?
Run this command "npm install yargs" and retry

**Comment by G0053-Ma5t3r** [comment]
Hey! Thanks for getting back to me so quickly.
I've installed yargs now but it seems like there are quite a few other dependencies.
I'm now trying to install @truffle/hdwallet-provider but I'm getting a whole heap of errors.
I've attached an archive of the npm _logs directory.
Best,
anon

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by clovisjohn** [comment]
You shouldn't have to install packages manually
All the required packages are specified in package.json
You just have to run "npm install" in the folder containing package.json
